"""Catalog 50 khóa học mở rộng cho bộ dữ liệu learner-lifecycle."""

REJECTION_REASON = "Cần bổ sung ví dụ thực hành và tiêu chí đánh giá đầu ra trước khi phát hành."

COURSES_50: tuple[dict, ...] = (
    # ── Lập trình Web (6 ACTIVE) ──────────────────────────────────────────────
    {
        "slug": "react-19-full-stack-2026",
        "name": "Lập trình React 19 Full-Stack",
        "description": "Xây dựng ứng dụng web hiện đại với React 19, Server Components và Suspense. Kết hợp với Node.js và PostgreSQL để tạo sản phẩm hoàn chỉnh.",
        "objectives": "Nắm vững React 19 hooks, Server Components, Suspense; xây dựng được CRUD app hoàn chỉnh kết nối backend REST API.",
        "prerequisites": "Biết HTML/CSS cơ bản, JavaScript ES6+.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "nextjs-15-production-2026",
        "name": "Next.js 15 - Ứng dụng Production",
        "description": "Học cách triển khai ứng dụng Next.js 15 production-ready với App Router, Server Actions, và tích hợp Vercel.",
        "objectives": "Sử dụng thành thạo App Router, Server Actions, ISR và SSR; triển khai ứng dụng lên Vercel và tự định cấu hình CI/CD.",
        "prerequisites": "Đã biết React cơ bản và JavaScript.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "typescript-mastery-2026",
        "name": "TypeScript Nâng Cao cho Dự Án Thực Tế",
        "description": "Từ cơ bản đến nâng cao: generic types, conditional types, mapped types và tích hợp TypeScript vào dự án React và Node.js quy mô lớn.",
        "objectives": "Viết code TypeScript chặt chẽ; sử dụng utility types; tạo type-safe API client; áp dụng design pattern với TypeScript.",
        "prerequisites": "Biết JavaScript ES6+ và có kinh nghiệm lập trình cơ bản.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "html-css-advanced-2026",
        "name": "HTML5 & CSS3 Nâng Cao - Layout và Animation",
        "description": "Kỹ thuật CSS Grid, Flexbox, CSS Variables và animation phức tạp. Xây dựng landing page responsive, accessible và đẹp mắt.",
        "objectives": "Thành thạo CSS Grid và Flexbox; tạo animation và transition mượt; xây dựng design system bằng CSS Variables.",
        "prerequisites": "Biết HTML/CSS cơ bản.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "vue3-composition-api-2026",
        "name": "Vue 3 với Composition API",
        "description": "Xây dựng ứng dụng SPA hiện đại bằng Vue 3, Composition API, Pinia state management và Vue Router 4.",
        "objectives": "Nắm vững Composition API và Pinia; xây dựng component tái sử dụng; tích hợp Vue 3 với REST API và GraphQL.",
        "prerequisites": "Biết JavaScript và có kinh nghiệm lập trình cơ bản.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "web-performance-optimization-2026",
        "name": "Tối Ưu Hiệu Năng Web Hiện Đại",
        "description": "Kỹ thuật tối ưu Core Web Vitals, lazy loading, code splitting, image optimization và caching strategy cho ứng dụng web production.",
        "objectives": "Đạt điểm Lighthouse >= 90; tối ưu LCP, FID, CLS; áp dụng kỹ thuật caching và CDN hiệu quả.",
        "prerequisites": "Có kinh nghiệm phát triển web front-end cơ bản.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    # ── Lập trình Backend (6 ACTIVE) ─────────────────────────────────────────
    {
        "slug": "spring-boot-microservices-2026",
        "name": "Spring Boot 3 Microservices với Kubernetes",
        "description": "Thiết kế và triển khai hệ thống microservices bằng Spring Boot 3, Spring Cloud, Kafka và Kubernetes trên môi trường production.",
        "objectives": "Thiết kế microservices architecture; sử dụng API Gateway, Service Discovery; triển khai trên Kubernetes và quản lý service mesh.",
        "prerequisites": "Biết Java cơ bản và OOP. Có kinh nghiệm REST API.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "nodejs-express-api-2026",
        "name": "Node.js & Express - Xây Dựng REST API",
        "description": "Xây dựng REST API mạnh mẽ bằng Node.js, Express, JWT authentication, MongoDB và Redis. Triển khai production với PM2 và Nginx.",
        "objectives": "Tạo REST API chuẩn RESTful; tích hợp JWT và refresh token; tối ưu query MongoDB; quản lý cache bằng Redis.",
        "prerequisites": "Biết JavaScript ES6+ và HTTP cơ bản.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "python-fastapi-backend-2026",
        "name": "Python FastAPI - Backend Hiệu Năng Cao",
        "description": "Xây dựng API backend với FastAPI, Pydantic v2, SQLAlchemy 2.0 và Alembic. Tích hợp async database, background tasks và WebSocket.",
        "objectives": "Tạo API async với FastAPI; thiết kế schema Pydantic; viết migration Alembic; tích hợp background task và WebSocket.",
        "prerequisites": "Biết Python 3.10+ và cơ bản về OOP.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "dotnet-aspnet-core-2026",
        "name": "ASP.NET Core 8 - API và Clean Architecture",
        "description": "Xây dựng hệ thống backend theo Clean Architecture với ASP.NET Core 8, Entity Framework Core, MediatR và CQRS pattern.",
        "objectives": "Áp dụng Clean Architecture; sử dụng CQRS với MediatR; viết unit test với xUnit; tích hợp Swagger và versioning API.",
        "prerequisites": "Biết C# cơ bản và lập trình hướng đối tượng.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "graphql-api-design-2026",
        "name": "Thiết Kế API với GraphQL",
        "description": "Học GraphQL từ schema design đến resolver, subscription và federation. Xây dựng API linh hoạt phục vụ frontend đa nền tảng.",
        "objectives": "Thiết kế GraphQL schema; viết resolver và mutation; cài đặt subscription với WebSocket; tối ưu N+1 query với DataLoader.",
        "prerequisites": "Biết REST API và JavaScript/Node.js cơ bản.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "backend-testing-strategy-2026",
        "name": "Chiến Lược Kiểm Thử Backend Toàn Diện",
        "description": "Unit test, integration test và contract test cho backend. Sử dụng JUnit 5, Mockito, Testcontainers và Pact để đảm bảo chất lượng.",
        "objectives": "Viết unit test và integration test đầy đủ; sử dụng Testcontainers; áp dụng TDD và thiết lập CI pipeline kiểm thử tự động.",
        "prerequisites": "Biết ít nhất một ngôn ngữ backend và có hiểu biết về REST API.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    # ── AI & Khoa học dữ liệu (5 ACTIVE) ─────────────────────────────────────
    {
        "slug": "machine-learning-python-2026",
        "name": "Machine Learning với Python từ A đến Z",
        "description": "Học toàn bộ nền tảng Machine Learning: linear regression, classification, clustering, ensemble methods và model evaluation với scikit-learn.",
        "objectives": "Hiểu và áp dụng các thuật toán ML cơ bản; tiền xử lý dữ liệu; đánh giá mô hình; triển khai model lên production.",
        "prerequisites": "Biết Python cơ bản và toán học đại học (đại số tuyến tính, xác suất).",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "deep-learning-pytorch-2026",
        "name": "Deep Learning với PyTorch",
        "description": "Xây dựng và huấn luyện mạng neural với PyTorch. CNN cho computer vision, RNN/LSTM cho time-series và Transformer cho NLP.",
        "objectives": "Xây dựng neural network với PyTorch; huấn luyện và fine-tune mô hình; tối ưu với GPU; deploy mô hình với TorchServe.",
        "prerequisites": "Có kiến thức Machine Learning cơ bản và biết Python.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "python-data-science-pandas-2026",
        "name": "Khoa Học Dữ Liệu với Pandas và NumPy",
        "description": "Phân tích và trực quan hóa dữ liệu chuyên nghiệp với Pandas, NumPy, Matplotlib và Seaborn. Xử lý dataset lớn và tạo báo cáo tự động.",
        "objectives": "Thành thạo Pandas dataframe; trực quan hóa dữ liệu; xử lý missing values và outliers; tự động hóa quy trình phân tích.",
        "prerequisites": "Biết Python cơ bản.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "nlp-llm-applications-2026",
        "name": "Ứng Dụng NLP và LLM trong Thực Tế",
        "description": "Xây dựng ứng dụng NLP với Hugging Face Transformers, fine-tune LLM, RAG pipeline và tích hợp OpenAI/Gemini API vào hệ thống thực.",
        "objectives": "Fine-tune transformer model; xây dựng RAG system; tích hợp LLM API; đánh giá và tối ưu hiệu năng mô hình ngôn ngữ lớn.",
        "prerequisites": "Biết Python và có kiến thức cơ bản về Deep Learning.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "mlops-production-2026",
        "name": "MLOps - Vận Hành AI/ML trong Production",
        "description": "Xây dựng pipeline MLOps hoàn chỉnh: từ data pipeline, model training, experiment tracking với MLflow đến CI/CD cho ML và monitoring.",
        "objectives": "Thiết kế MLOps pipeline; dùng MLflow và DVC; triển khai model với FastAPI và Docker; giám sát model drift.",
        "prerequisites": "Có kinh nghiệm ML cơ bản và biết Docker/Linux.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    # ── Cloud & DevOps (4 ACTIVE) ─────────────────────────────────────────────
    {
        "slug": "docker-kubernetes-2026",
        "name": "Docker và Kubernetes cho DevOps",
        "description": "Containerization với Docker, orchestration với Kubernetes. Triển khai ứng dụng microservices trên cluster Kubernetes production.",
        "objectives": "Viết Dockerfile tối ưu; quản lý Kubernetes pods, services, ingress; cấu hình autoscaling và monitoring với Prometheus.",
        "prerequisites": "Biết Linux cơ bản và có kinh nghiệm phát triển phần mềm.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "aws-cloud-architect-2026",
        "name": "Kiến Trúc AWS Cloud cho Ứng Dụng Doanh Nghiệp",
        "description": "Thiết kế và triển khai hạ tầng AWS production: EC2, ECS, RDS, S3, CloudFront, Lambda và IAM theo Well-Architected Framework.",
        "objectives": "Thiết kế kiến trúc AWS đáng tin cậy; cấu hình VPC, security group; tối ưu chi phí và hiệu năng; áp dụng Infrastructure as Code.",
        "prerequisites": "Biết Linux và có kiến thức cơ bản về networking.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "cicd-gitlab-jenkins-2026",
        "name": "CI/CD Pipeline với GitLab và Jenkins",
        "description": "Xây dựng CI/CD pipeline tự động hóa từ commit đến deployment. GitLab CI, Jenkins, SonarQube, Trivy và Helm trên Kubernetes.",
        "objectives": "Tạo pipeline CI/CD đầy đủ; tích hợp code quality và security scan; triển khai blue-green và canary deployment.",
        "prerequisites": "Biết Git, Docker cơ bản và có kinh nghiệm phát triển phần mềm.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "terraform-infrastructure-2026",
        "name": "Infrastructure as Code với Terraform",
        "description": "Quản lý hạ tầng cloud bằng Terraform. Viết module tái sử dụng, quản lý state, workspace và tích hợp với GitOps workflow.",
        "objectives": "Viết Terraform module chuẩn; quản lý remote state; áp dụng Terragrunt; tích hợp Terraform vào CI/CD pipeline.",
        "prerequisites": "Biết ít nhất một cloud provider và cơ bản về infrastructure.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    # ── An toàn thông tin (4 ACTIVE) ─────────────────────────────────────────
    {
        "slug": "owasp-web-security-2026",
        "name": "Bảo Mật Web theo OWASP Top 10",
        "description": "Tìm hiểu và phòng chống Top 10 lỗ hổng OWASP: SQL Injection, XSS, CSRF, SSRF, Broken Authentication và các kỹ thuật hardening web.",
        "objectives": "Nhận biết và khai thác lỗ hổng OWASP Top 10; áp dụng biện pháp phòng chống; thực hiện code review bảo mật.",
        "prerequisites": "Biết cơ bản về web development và HTTP.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "penetration-testing-2026",
        "name": "Kiểm Thử Xâm Nhập (Penetration Testing)",
        "description": "Học kỹ thuật pentest chuyên nghiệp: reconnaissance, vulnerability scanning, exploitation và reporting. Dùng Kali Linux, Metasploit và Burp Suite.",
        "objectives": "Thực hiện pentest theo methodology chuẩn; sử dụng Burp Suite và Metasploit thành thạo; viết báo cáo pentest chuyên nghiệp.",
        "prerequisites": "Biết Linux, networking cơ bản và có đạo đức nghề nghiệp.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "cryptography-applied-2026",
        "name": "Mật Mã Học Ứng Dụng",
        "description": "Nền tảng mật mã học hiện đại: symmetric và asymmetric encryption, hash functions, digital signatures, PKI và TLS/SSL protocol.",
        "objectives": "Hiểu nguyên lý mã hóa AES, RSA, ECC; triển khai TLS đúng cách; sử dụng thư viện crypto an toàn trong ứng dụng.",
        "prerequisites": "Biết toán học đại số và cơ bản về lập trình.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "network-security-2026",
        "name": "An Ninh Mạng và Phòng Thủ Hệ Thống",
        "description": "Thiết kế kiến trúc mạng an toàn, cấu hình firewall, IDS/IPS, VPN và giám sát bảo mật với SIEM. Ứng phó sự cố bảo mật.",
        "objectives": "Thiết kế DMZ và segmentation; cấu hình Snort/Suricata; phân tích log với ELK SIEM; xây dựng incident response plan.",
        "prerequisites": "Biết networking (TCP/IP, routing, switching) và Linux.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    # ── Mobile (3 ACTIVE) ─────────────────────────────────────────────────────
    {
        "slug": "flutter-mobile-2026",
        "name": "Flutter - Ứng Dụng Di Động Đa Nền Tảng",
        "description": "Xây dựng ứng dụng mobile iOS và Android với Flutter, Dart và BLoC pattern. Tích hợp Firebase, REST API và publish lên store.",
        "objectives": "Xây dựng UI responsive với Flutter; sử dụng BLoC/Riverpod; tích hợp Firebase Auth và Firestore; deploy lên App Store và Google Play.",
        "prerequisites": "Biết lập trình hướng đối tượng và cơ bản về mobile.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "react-native-mobile-2026",
        "name": "React Native - App Mobile với JavaScript",
        "description": "Phát triển ứng dụng mobile cross-platform với React Native, Expo và Redux Toolkit. Navigation, animations và tích hợp native modules.",
        "objectives": "Tạo UI mobile native với React Native; cấu hình React Navigation; sử dụng Expo EAS Build; tích hợp camera, maps và push notification.",
        "prerequisites": "Biết React và JavaScript ES6+.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "ios-swift-development-2026",
        "name": "Lập Trình iOS với Swift",
        "description": "Xây dựng ứng dụng iOS native với Swift, SwiftUI và UIKit. Tích hợp Core Data, CloudKit và submit lên App Store.",
        "objectives": "Tạo UI với SwiftUI; quản lý dữ liệu với Core Data; tích hợp CloudKit; thực hiện App Store submission thành công.",
        "prerequisites": "Biết lập trình cơ bản và có macOS để phát triển.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    # ── Cơ sở dữ liệu (3 ACTIVE) ──────────────────────────────────────────────
    {
        "slug": "sql-advanced-2026",
        "name": "SQL Nâng Cao và Tối Ưu Truy Vấn",
        "description": "Window functions, CTE, stored procedures, triggers và kỹ thuật tối ưu query. Phân tích execution plan và xử lý database lớn.",
        "objectives": "Viết query phức tạp với window functions; phân tích và tối ưu execution plan; thiết kế partition và index chiến lược.",
        "prerequisites": "Biết SQL cơ bản (SELECT, JOIN, GROUP BY).",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "redis-caching-2026",
        "name": "Redis - Caching và Message Broker",
        "description": "Thiết kế cache strategy với Redis: data structures, pub/sub, streams, Redis Cluster và tích hợp với ứng dụng Node.js và Python.",
        "objectives": "Sử dụng Redis data structures phù hợp; thiết kế cache invalidation; cấu hình Redis Cluster; xây dựng pub/sub messaging.",
        "prerequisites": "Biết cơ bản về database và có kinh nghiệm backend.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "mongodb-nosql-2026",
        "name": "MongoDB và NoSQL Design Pattern",
        "description": "Thiết kế schema MongoDB hiệu quả, aggregation pipeline, indexing strategy và sharding. Pattern embedding vs referencing và khi nào dùng NoSQL.",
        "objectives": "Thiết kế schema MongoDB phù hợp use case; viết aggregation pipeline phức tạp; cấu hình replica set và sharding.",
        "prerequisites": "Biết SQL cơ bản và có kiến thức về database.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    # ── Tiếng Anh (3 ACTIVE) ──────────────────────────────────────────────────
    {
        "slug": "business-english-communication-2026",
        "name": "Tiếng Anh Giao Tiếp Công Sở",
        "description": "Phát triển kỹ năng tiếng Anh trong môi trường công sở: email chuyên nghiệp, thuyết trình, họp nhóm quốc tế và đàm phán.",
        "objectives": "Viết email business chuẩn; thuyết trình tiếng Anh tự tin; giao tiếp trong meeting quốc tế; xử lý tình huống khó bằng tiếng Anh.",
        "prerequisites": "Trình độ tiếng Anh B1 trở lên (tương đương IELTS 5.0).",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "ielts-academic-2026",
        "name": "IELTS Academic - Chinh Phục Band 6.5+",
        "description": "Chiến lược và luyện tập toàn diện 4 kỹ năng IELTS Academic: Listening, Reading, Writing Task 1&2 và Speaking với band target 6.5+.",
        "objectives": "Đạt IELTS 6.5+; nắm vững chiến lược làm bài; viết essay Academic Task 2 coherent; speaking band 6.5 với fluency và vocabulary.",
        "prerequisites": "Trình độ tiếng Anh B1 (IELTS 5.0 tương đương) và quyết tâm học tập.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "technical-english-it-2026",
        "name": "Tiếng Anh Kỹ Thuật cho Lập Trình Viên",
        "description": "Đọc hiểu documentation, viết technical specification, trao đổi với khách hàng nước ngoài và tham gia code review bằng tiếng Anh.",
        "objectives": "Đọc hiểu technical documentation nhanh; viết ticket và spec rõ ràng; giao tiếp với offshore team; làm technical interview tiếng Anh.",
        "prerequisites": "Biết lập trình cơ bản và có trình độ tiếng Anh A2 trở lên.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    # ── Kỹ năng mềm (3 ACTIVE) ───────────────────────────────────────────────
    {
        "slug": "time-management-agile-2026",
        "name": "Quản Lý Thời Gian và Làm Việc Agile",
        "description": "Kỹ thuật quản lý thời gian hiệu quả (Pomodoro, GTD, Eisenhower Matrix) kết hợp với quy trình Agile/Scrum trong môi trường dự án IT.",
        "objectives": "Áp dụng GTD và Pomodoro hiệu quả; hiểu Scrum ceremonies; làm việc hiệu quả trong team Agile; quản lý backlog và sprint.",
        "prerequisites": "Không yêu cầu. Phù hợp cho tất cả mọi người.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "presentation-skills-2026",
        "name": "Kỹ Năng Thuyết Trình Chuyên Nghiệp",
        "description": "Thiết kế slide đẹp, xây dựng cấu trúc câu chuyện, khắc phục lo âu và trình bày tự tin trước đám đông trong các tình huống công việc.",
        "objectives": "Thiết kế slide theo nguyên tắc Zen; xây dựng story line thuyết phục; kiểm soát ngôn ngữ cơ thể và giọng nói; xử lý câu hỏi tự tin.",
        "prerequisites": "Không yêu cầu kinh nghiệm thuyết trình trước.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "teamwork-leadership-2026",
        "name": "Làm Việc Nhóm và Phát Triển Kỹ Năng Lãnh Đạo",
        "description": "Xây dựng kỹ năng làm việc nhóm hiệu quả, giải quyết xung đột, give & receive feedback và phát triển tư duy lãnh đạo servant leadership.",
        "objectives": "Giao tiếp và hợp tác nhóm tốt hơn; giải quyết xung đột xây dựng; give feedback STAR; hiểu và áp dụng servant leadership.",
        "prerequisites": "Không yêu cầu. Phù hợp cho tất cả mọi người.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "ACTIVE",
    },
    # ── Thiết kế UI/UX (3 ACTIVE) ─────────────────────────────────────────────
    {
        "slug": "figma-ui-design-2026",
        "name": "Thiết Kế UI với Figma - Từ Wireframe đến Prototype",
        "description": "Học Figma từ cơ bản đến nâng cao: auto layout, component, variant, interactive prototype và handoff với developer.",
        "objectives": "Sử dụng thành thạo Figma; tạo component library; xây dựng interactive prototype; handoff với developer qua Figma Dev Mode.",
        "prerequisites": "Có khiếu thẩm mỹ cơ bản và biết dùng máy tính.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "design-system-2026",
        "name": "Xây Dựng Design System cho Doanh Nghiệp",
        "description": "Thiết kế và duy trì Design System hoàn chỉnh: color token, typography, component library, documentation và governance process.",
        "objectives": "Tạo Design System từ đầu; quản lý token và theme; xây dựng Storybook component; thiết lập governance và contribution guidelines.",
        "prerequisites": "Biết Figma và có kinh nghiệm thiết kế UI cơ bản.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau1.mp4"),
        "target_status": "ACTIVE",
    },
    {
        "slug": "ux-research-2026",
        "name": "Nghiên Cứu Trải Nghiệm Người Dùng (UX Research)",
        "description": "Phương pháp UX Research chuyên nghiệp: user interview, usability testing, card sorting, A/B testing và tổng hợp insight ra quyết định.",
        "objectives": "Thực hiện user interview chuyên nghiệp; tiến hành usability test; phân tích và tổng hợp insight; trình bày kết quả cho stakeholder.",
        "prerequisites": "Quan tâm đến người dùng và có kỹ năng giao tiếp tốt.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau3.mp4"),
        "target_status": "ACTIVE",
    },
    # ── DRAFT (4 khóa) ────────────────────────────────────────────────────────
    {
        "slug": "rust-systems-programming-draft-2026",
        "name": "Lập Trình Systems với Rust - Bản Nháp",
        "description": "Bản nháp giới thiệu Rust cho lập trình systems: ownership, borrowing, lifetime và concurrency an toàn. Đang biên soạn nội dung thực hành.",
        "objectives": "Hiểu ownership model; viết code an toàn không có data race; tương tác với C qua FFI.",
        "prerequisites": "Có kinh nghiệm lập trình C hoặc ngôn ngữ systems khác.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "DRAFT",
    },
    {
        "slug": "blockchain-web3-draft-2026",
        "name": "Blockchain và Web3 Development - Bản Nháp",
        "description": "Đang biên soạn: smart contract với Solidity, DApp với ethers.js và tích hợp MetaMask. Nội dung đang được review bởi chuyên gia.",
        "objectives": "Viết và deploy smart contract; xây dựng DApp cơ bản; tương tác với blockchain qua Web3.",
        "prerequisites": "Biết JavaScript và có kiến thức cơ bản về blockchain.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau2.mp4"),
        "target_status": "DRAFT",
    },
    {
        "slug": "game-development-unity-draft-2026",
        "name": "Phát Triển Game với Unity - Bản Nháp",
        "description": "Đang biên soạn: xây dựng game 2D và 3D với Unity, C# scripting, physics engine và publish lên PC và mobile.",
        "objectives": "Tạo game 2D hoàn chỉnh; sử dụng Unity physics; implement game mechanics cơ bản.",
        "prerequisites": "Biết lập trình hướng đối tượng cơ bản.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "DRAFT",
    },
    {
        "slug": "embedded-iot-draft-2026",
        "name": "Lập Trình Nhúng và IoT - Bản Nháp",
        "description": "Đang xây dựng nội dung về lập trình Arduino, Raspberry Pi, MQTT protocol và kết nối thiết bị IoT với cloud platform.",
        "objectives": "Lập trình Arduino và Raspberry Pi; giao tiếp với sensors; gửi dữ liệu lên MQTT broker.",
        "prerequisites": "Biết C cơ bản và có hứng thú với phần cứng.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau1.mp4"),
        "target_status": "DRAFT",
    },
    # ── PENDING (3 khóa) ──────────────────────────────────────────────────────
    {
        "slug": "golang-backend-pending-2026",
        "name": "Lập Trình Backend với Go (Golang) - Chờ Duyệt",
        "description": "Khóa học đã hoàn thiện về Go: goroutines, channels, gRPC, Gin framework và deploy microservices production. Đang chờ phê duyệt.",
        "objectives": "Viết Go idiomatic; sử dụng goroutine và channel hiệu quả; xây dựng gRPC service; tối ưu hiệu năng với profiling.",
        "prerequisites": "Biết lập trình và có kinh nghiệm backend cơ bản.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau1.mp4"),
        "target_status": "PENDING",
    },
    {
        "slug": "agile-scrum-master-pending-2026",
        "name": "Agile Scrum Master Certification Prep - Chờ Duyệt",
        "description": "Chuẩn bị thi chứng chỉ PSM I/CSM: Scrum framework, ceremonies, artifacts, scaling Agile với SAFe và thực hành retrospective.",
        "objectives": "Hiểu sâu Scrum Guide; dẫn dắt retrospective và sprint planning; áp dụng SAFe trong tổ chức lớn; chuẩn bị thi PSM I.",
        "prerequisites": "Có ít nhất 6 tháng làm việc trong môi trường Agile.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau2.mp4"),
        "target_status": "PENDING",
    },
    {
        "slug": "product-management-it-pending-2026",
        "name": "Product Management cho Dự Án IT - Chờ Duyệt",
        "description": "Kỹ năng quản lý sản phẩm IT: user story mapping, prioritization framework, product roadmap, OKR và làm việc với dev team.",
        "objectives": "Viết user story INVEST; prioritize backlog với RICE; xây dựng product roadmap; đo lường product metrics và ra quyết định data-driven.",
        "prerequisites": "Có kinh nghiệm làm việc trong môi trường IT.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau3.mp4"),
        "target_status": "PENDING",
    },
    # ── REJECTED (3 khóa) ─────────────────────────────────────────────────────
    {
        "slug": "php-laravel-rejected-2026",
        "name": "PHP Laravel - Cần Bổ Sung Nội Dung",
        "description": "Khóa học Laravel đã gửi duyệt nhưng cần bổ sung thêm bài thực hành deployment và bài kiểm tra cuối khóa.",
        "objectives": "Xây dựng ứng dụng với Laravel; sử dụng Eloquent ORM; tích hợp Sanctum authentication.",
        "prerequisites": "Biết PHP cơ bản và MVC pattern.",
        "image": "c3.jpg",
        "videos": ("mau3.mp4", "mau2.mp4"),
        "target_status": "REJECTED",
    },
    {
        "slug": "jquery-legacy-rejected-2026",
        "name": "jQuery và JavaScript Cổ Điển - Cần Cập Nhật",
        "description": "Nội dung cần cập nhật để phù hợp với xu hướng hiện tại. Admin đề nghị bổ sung so sánh với vanilla JS modern và lộ trình migration.",
        "objectives": "Sử dụng jQuery animation và AJAX; hiểu khi nào nên dùng jQuery.",
        "prerequisites": "Biết HTML/CSS và JavaScript cơ bản.",
        "image": "c1.jpg",
        "videos": ("mau1.mp4", "mau3.mp4"),
        "target_status": "REJECTED",
    },
    {
        "slug": "excel-data-analysis-rejected-2026",
        "name": "Phân Tích Dữ Liệu với Excel - Cần Bổ Sung",
        "description": "Khóa học Excel cho data analysis cần bổ sung thêm case study thực tế và tích hợp với Power BI theo yêu cầu của admin.",
        "objectives": "Sử dụng pivot table; viết formula nâng cao; tạo dashboard Excel chuyên nghiệp.",
        "prerequisites": "Biết Excel cơ bản.",
        "image": "c2.jpg",
        "videos": ("mau2.mp4", "mau1.mp4"),
        "target_status": "REJECTED",
    },
)

assert len(COURSES_50) == 50, f"Expected 50 courses, got {len(COURSES_50)}"
assert sum(1 for c in COURSES_50 if c["target_status"] == "ACTIVE") == 40
assert sum(1 for c in COURSES_50 if c["target_status"] == "DRAFT") == 4
assert sum(1 for c in COURSES_50 if c["target_status"] == "PENDING") == 3
assert sum(1 for c in COURSES_50 if c["target_status"] == "REJECTED") == 3
