import httpClient from "@/api/httpClient";
import type { ApiResponse } from "@/types/base";

export const adminCourseClassApi = {
  getCourses: async () => (await httpClient.get<ApiResponse<any[]>>("/v1/courses")).data.data || [],
  getCourse: async (id: string | number) => (await httpClient.get<ApiResponse<any>>(`/v1/courses/${id}`)).data.data,
  getCategories: async () => (await httpClient.get<ApiResponse<any[]>>("/v1/categories")).data.data || [],
  getPackages: async () => (await httpClient.get<ApiResponse<any[]>>("/v1/course-packages")).data.data || [],
  getPackagesByCourse: async (courseId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/course-packages/course/${courseId}`)).data.data || [],
  createPackage: async (payload: any) => (await httpClient.post<ApiResponse<any>>("/v1/course-packages", payload)).data.data,
  updatePackage: async (id: string | number, payload: any) => (await httpClient.put<ApiResponse<any>>(`/v1/course-packages/${id}`, payload)).data.data,
  deletePackage: async (id: string | number) => httpClient.delete(`/v1/course-packages/${id}`),
  getClasses: async () => (await httpClient.get<ApiResponse<any[]>>("/v1/classes")).data.data || [],
  getClass: async (id: string | number) => (await httpClient.get<ApiResponse<any>>(`/v1/classes/${id}`)).data.data,
  getClassesByCourse: async (courseId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/classes/course/${courseId}`)).data.data || [],
  createClass: async (payload: any) => (await httpClient.post<ApiResponse<any>>("/v1/classes", payload)).data.data,
  createGroupClass: async (payload: any) => (await httpClient.post<ApiResponse<any>>("/v1/class_managements/classes", payload)).data.data,
  updateClass: async (id: string | number, payload: any) => (await httpClient.put<ApiResponse<any>>(`/v1/classes/${id}`, payload)).data.data,
  deleteClass: async (id: string | number) => httpClient.delete(`/v1/classes/${id}`),
  getClassSessions: async (classId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/class-online/class/${classId}`)).data.data || [],
  getClassMembers: async (classId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/classes/${classId}/members`)).data.data || [],
  getClassSchedules: async (classId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/classes/${classId}/schedules`)).data.data || [],
  getCourseTeachers: async (courseId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/course-teachers/course/${courseId}`)).data.data || [],
  getClassEnrollments: async (classId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/enrollments/class/${classId}`)).data.data || [],
  getTeachingRates: async () => (await httpClient.get<ApiResponse<any[]>>("/v1/teaching-rates")).data.data || [],
  getTeachingPayments: async () => (await httpClient.get<ApiResponse<any[]>>("/v1/teaching-session-payments")).data.data || [],
  getEmployees: async () => (await httpClient.get<ApiResponse<any[]>>("/v1/employees")).data.data || [],
  getTeacherCategories: async () => (await httpClient.get<ApiResponse<any[]>>("/v1/teacher_categories/teacher-categories")).data.data || [],
  getSections: async (courseId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/courses/${courseId}/sections`)).data.data || [],
  getLessons: async (sectionId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/lessons/sections/${sectionId}`)).data.data || [],
  getLesson: async (lessonId: string | number) => (await httpClient.get<ApiResponse<any>>(`/v1/lessons/${lessonId}`)).data.data,
  getLessonResources: async (lessonId: string | number) => (await httpClient.get<ApiResponse<any[]>>(`/v1/lesson-resources/lessons/${lessonId}/resources`)).data.data || [],
};
