spring:
  application:
    name: ai-lms
  datasource:
    url: jdbc:mysql://localhost:3306/ailms
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ##(create, update, create-drop, validate)
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080

api:
  prefix: /api/v1
  auth-prefix: /api/auth


app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 900000 # 15 minutes - thời gian sống của access token
    refresh-expiration-ms: 604800000 # 7 days - thời gian sống của refresh token
  frontend:
    url: "http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000"
    set-password: "http://localhost:8080"
  otp:
    expiration-minutes: 3
  cookie:
    secure: false
    same-site: None