spring:
  application:
    name: ai-lms
  datasource:
    url: jdbc:mysql://localhost:3306/ailms
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ##(create, update, create-drop, validate)
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

server:
  port: 8080

api:
  prefix: /api/v1