
spring:
  application:
    name: ai-lms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ailms}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ##(create, update, create-drop, validate)
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      repositories:
#        Khong check repository redis
        enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:seed}
# active: seed -> run dataseeder
server:
  port: 8080

api:
  prefix: /api/v1
  auth-prefix: /api/auth


app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 604800000 # 15 minutes - thời gian sống của access token
    refresh-expiration-ms: 604800000 # 7 days - thời gian sống của refresh token
  frontend:
    url: ${FRONTEND_URL:http://localhost,http://localhost:80,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000,http://213.163.201.42,https://datdepzaivcl.taile009f4.ts.net}
    set-password: ${FRONTEND_SET_PASSWORD_URL:http://localhost:5173/set-password}
  otp:
    expiration-minutes: 3
  cookie:
    secure: false
    same-site: Lax

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  external-endpoint: ${MINIO_EXTERNAL_ENDPOINT:${minio.endpoint}}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket-name: ${MINIO_BUCKET_NAME:ailms-minio}

ai-service:
  base-url: http://localhost:8000
  interal-token: dev_internal_secret_123

paypal:
  client-id: ${PAYPAL_CLIENT_ID:}
  client-secret: ${PAYPAL_CLIENT_SECRET:}
  api-base-url: ${PAYPAL_API_BASE_URL:https://api-m.sandbox.paypal.com}
  return-url: ${PAYPAL_RETURN_URL:http://localhost/payment/result}
  cancel-url: ${PAYPAL_CANCEL_URL:http://localhost/payment/result?cancelled=1}
  currency: ${PAYPAL_CURRENCY:USD}
  vnd-per-unit: ${PAYPAL_VND_PER_UNIT:26000}
